name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Generate package-lock.json if not exists
        run: |
          npm install --package-lock-only

          # Check if package-lock.json was generated
          if [ ! -f "package-lock.json" ]; then
            echo "Error: package-lock.json not generated"
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test
